### ISSUE TITLE
Not working in 1.9.2.1 magento

### ISSUE THREAD

**Issue by Jocika1990** [husseycoding/cartrulefix#4]
Hi,

I added this to 1.9.2.1 and it is not working.
Do you know what can be the issue?

Thanks

**Comment by husseycoding** [comment]
This is pretty old now and we don't maintain it anymore - it was only added as an immediate fix after the release of 1.9CE, it's very possible that the logic here has changed in the core now so this fix may no longer work, but we haven't tested it since initial release.  We don't have any plans to do any further work here, but feel free to look at it yourself as it's completely open source.
